name: Release
on:
  push:
    branches:
      - "main"
      - "next"
      - "beta"
jobs:
  release:
    name: Release new build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build project
      run: npm run build
    - name: Release
      run: npx semantic-release
